name: build-boot-vince-working
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone kernel vatva 4.9
        run: |
          rm -rf kernel
          git clone --depth 1 https://github.com/vatva691/android_kernel_xiaomi_msm8953-4.9 kernel || git clone --depth 1 https://github.com/vatva691/android_kernel_xiaomi_msm8953-4.9 -b lineage-20 kernel
          ls kernel/arch/arm64/configs/*vince*
          cat kernel/arch/arm64/configs/vince-perf_defconfig > kernel/arch/arm64/configs/droidian_defconfig
          cat >> kernel/arch/arm64/configs/droidian_defconfig <<'EOF'
          CONFIG_DEVTMPFS=y
          CONFIG_DEVTMPFS_MOUNT=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_VT=y
          CONFIG_NAMESPACES=y
          CONFIG_PID_NS=y
          CONFIG_NET_NS=y
          CONFIG_IPC_NS=y
          CONFIG_CGROUPS=y
          CONFIG_CGROUP_DEVICE=y
          CONFIG_CGROUP_FREEZER=y
          CONFIG_CGROUP_PIDS=y
          CONFIG_MEMCG=y
          CONFIG_OVERLAY_FS=y
          CONFIG_FHANDLE=y
          CONFIG_SECCOMP=y
          CONFIG_SECCOMP_FILTER=y
          CONFIG_VETH=y
          CONFIG_BRIDGE=y
          CONFIG_AUTOFS4_FS=y
          CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
          CONFIG_USB_CONFIGFS_RNDIS=y
          EOF

      - name: Build Image.gz-dtb
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-10-aarch64-linux-gnu bc bison flex libssl-dev libelf-dev
          cd kernel
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-gcc-10- droidian_defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-gcc-10- -j2 Image.gz
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-gcc-10- -j2 dtbs
          cat arch/arm64/boot/Image.gz arch/arm64/boot/dts/qcom/msm8953-vince*.dtb > ../Image.gz-dtb
          ls -lh ../Image.gz-dtb

      - name: Make boot.img Droidian
        run: |
          cd $GITHUB_WORKSPACE
          echo -n | gzip > ramdisk.cpio.gz
          wget -q https://github.com/osm0x/android-prebuilt-mkbootimg/releases/download/20200505/mkbootimg -O mkbootimg
          chmod +x mkbootimg
          ./mkbootimg --kernel Image.gz-dtb --ramdisk ramdisk.cpio.gz --base 0x80000000 --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --pagesize 2048 --cmdline "androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci androidboot.selinux=permissive droidian.lvm.prefer" -o boot-vince-A13-droidian.img
          ls -lh boot*.img

      - name: Upload boot
        uses: actions/upload-artifact@v4
        with:
          name: boot-working-vince
          path: boot-vince-A13-droidian.img
